/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caspersfilmregister;

import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Casper Björk
 */
public class FilmRegisterGUI extends javax.swing.JFrame {

    /**
     * Creates new form FilmRegisterGUI
     */
    private DefaultTableModel model;
    private Form DialogForm;
    private Delete deleteSelected;
    private int lastClickedRow;

    public FilmRegisterGUI() {
        initComponents();
        model = (DefaultTableModel) Register_1.getModel();
        DialogForm = new Form();
        deleteSelected = new Delete();
        lastClickedRow = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        btn_insertFilm = new javax.swing.JButton();
        btn_insertGenre = new javax.swing.JButton();
        btn_insertRegissor = new javax.swing.JButton();
        btn_dlt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Register_1 = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Filmregister");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Filmregister av Casper Björk");

        btn_refresh.setText("Refresh");
        btn_refresh.setToolTipText("");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_insertFilm.setText("Lägg till film");
        btn_insertFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertFilmActionPerformed(evt);
            }
        });

        btn_insertGenre.setText("Lägg till Genre");
        btn_insertGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertGenreActionPerformed(evt);
            }
        });

        btn_insertRegissor.setText("Lägg till Regissör");
        btn_insertRegissor.setToolTipText("");
        btn_insertRegissor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertRegissorActionPerformed(evt);
            }
        });

        btn_dlt.setText("Delete");
        btn_dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(btn_insertFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btn_insertGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btn_insertRegissor)
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_dlt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(353, 353, 353)
                .addComponent(btn_refresh)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refresh)
                    .addComponent(btn_dlt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insertRegissor)
                    .addComponent(btn_insertGenre)
                    .addComponent(btn_insertFilm))
                .addContainerGap())
        );

        Register_1.setAutoCreateRowSorter(true);
        Register_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Namn", "Genre", "Betyg", "Regissör"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Register_1.setToolTipText("Tabell för registret");
        Register_1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Register_1.setEditingColumn(0);
        Register_1.setEditingRow(0);
        Register_1.getTableHeader().setReorderingAllowed(false);
        Register_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Register_1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Register_1);
        if (Register_1.getColumnModel().getColumnCount() > 0) {
            Register_1.getColumnModel().getColumn(0).setMinWidth(0);
            Register_1.getColumnModel().getColumn(0).setPreferredWidth(0);
            Register_1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.out.println("Bye!");
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        refresh();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_insertFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertFilmActionPerformed
        //Insert Film Form
        DialogForm.clearGUI();
        DialogForm.createMovieForm();
        refresh();
    }//GEN-LAST:event_btn_insertFilmActionPerformed

    private void btn_insertGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertGenreActionPerformed
        //Insert Genre Form
        DialogForm.clearGUI();
        DialogForm.createGenreForm();
        refresh();
    }//GEN-LAST:event_btn_insertGenreActionPerformed

    private void btn_insertRegissorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertRegissorActionPerformed
        //Insert Regissor Form
        DialogForm.clearGUI();
        DialogForm.createRegissorForm();
        refresh();
    }//GEN-LAST:event_btn_insertRegissorActionPerformed

    private void btn_dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dltActionPerformed
        //Delete content
        if (lastClickedRow == 0) {
            JOptionPane.showMessageDialog(this, "Ni har inte valt något att ta bort!", "Fel", HEIGHT);
        } else {
            int IDtoDLT = Integer.parseInt(String.valueOf(model.getValueAt(lastClickedRow, 0)));
            int confirm = JOptionPane.showConfirmDialog(this, "Är du säker på att du vill ta bort: "+ String.valueOf(model.getValueAt(lastClickedRow, 1))+"?");
            
            if (confirm == 1 || confirm == 2) {
                System.out.println("Avbröt bortagelsen av Film");
            } else {
                deleteSelected.RemoveData(IDtoDLT);
                refresh();
            }
            refresh();
        }

    }//GEN-LAST:event_btn_dltActionPerformed

    private void Register_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Register_1MouseClicked
        lastClickedRow = Register_1.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_Register_1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmRegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmRegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmRegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmRegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmRegisterGUI().setVisible(true);
            }
        });
    }
    /**
     * <h1>Refreshed the table</h1>
     * <p>Will pull all movie data from the database and put it in to rows and add it to the table</p>
     */
    public void refresh() {
        model.setRowCount(0);
        String titel;
        ResultSet data = null;
        Statement stmt = null;
        try {
            Connection connection = ConnectDBFactory.getConnection();
            stmt = connection.createStatement();
            data = stmt.executeQuery("SELECT film.id,film.Titel,film.Släpptes,genre.Namn_Genre,film.Betyg,regissor.regissor_Namn FROM film,genre,regissor WHERE film.Genre = genre.Genre_id AND film.Regissor = regissor.regissor_id ");
            while (data.next()) {
                titel = data.getString("Titel") + " " + "(" + data.getInt("Släpptes") + ")";
                model.addRow(new Object[]{data.getInt("ID"), titel, data.getString("Namn_Genre"), data.getInt("Betyg"), data.getString("regissor_Namn")});
            }
        } catch (Exception e) {
            System.out.println(e);
        } finally {
            if (stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException ex) {
                    System.out.println("Stmt close " + ex);
                }
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Register_1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btn_dlt;
    private javax.swing.JButton btn_insertFilm;
    private javax.swing.JButton btn_insertGenre;
    private javax.swing.JButton btn_insertRegissor;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
